### ISSUE TITLE
node_modules/react-native-vision-camera-text-recognition/android/src/main/java/com/visioncameratextrecognition/VisionCameraTranslator.kt:101:13 Unresolved reference: Orientation

### ISSUE THREAD

**Issue by shishi-RN** [gev2002/react-native-vision-camera-text-recognition#11]
node_modules/react-native-vision-camera-text-recognition/android/src/main/java/com/visioncameratextrecognition/VisionCameraTranslator.kt:101:13 Unresolved reference: Orientation

**Comment by gev2002** [comment]
It's same problem like this. [#2247210816](https://github.com/gev2002/react-native-vision-camera-image-labeler/issues/7#issuecomment-2247210816)

**Comment by shishi-RN** [comment]
Hi, I encountered another issue while launching the app. It crashes when opening the camera, but the app works when isActive={false}

**Comment by gev2002** [comment]
I also tested this package again, there are no problems with Android, there is only a problem with the IOS orientation, because orientation works differently now I will change it soon.

**Comment by zzz08900** [comment]
Would you take a look at this? 
https://github.com/gev2002/react-native-vision-camera-barcodes-scanner/issues/4

Seems to be the same problem.

**Comment by gev2002** [comment]
Orientation bug is fixed.
@zzz08900  I'll review that.
