### ISSUE TITLE
Frame processor OCR isn't working when the app is in landscape orientation

### ISSUE THREAD

**Issue by briazzi64** [gev2002/react-native-vision-camera-text-recognition#13]
My app doesn't allow landscape orientation and I'm curious if that is the problem. The photo recognizer function has an orientation prop but I can't find one for the camera. I can get the frame process OCR to work if I the text is portrait but the image is an envelope and it's awkward to have to stand so far back to the whole envelope in frame for portrait.

**Comment by denisbevilacqua** [comment]
You can take a photo and use the photo recognizer using the orientation prop if you want to use the landscape mode. For live detection, this library does not support yet Orientation and only will work in Portrait mode.

[Here](https://github.com/mrousavy/react-native-vision-camera/issues/3051#issuecomment-2228648294) the author of Vision Camera explains how to add support for Orientation to this library.

[Here](https://github.com/mrousavy/react-native-vision-camera/pull/3077) is more information about Orientation.

**Comment by briazzi64** [comment]
Awesome. Thanks for the info

**Comment by denisbevilacqua** [comment]
> Awesome. Thanks for the info

No problem! I created a new issue with the [Feature Request](https://github.com/gev2002/react-native-vision-camera-text-recognition/issues/17)!
