### ISSUE TITLE
Errors during build

### ISSUE THREAD

**Issue by margotbignon** [gev2002/react-native-vision-camera-text-recognition#15]
Hi,
I try to install Text Recognition,  there is my setup : 
    "react-native-vision-camera": "4.5.1",
    "react-native-vision-camera-text-recognition": "^3.1.1",
    "react-native-worklets-core": "^1.3.3",

I've a lot of errors during building of my app : 

The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (161, 18): Suspend function 'findCameraView' should be called only from a coroutine or another suspend function
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (162, 7): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (163, 14): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (172, 18): Suspend function 'findCameraView' should be called only from a coroutine or another suspend function
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (173, 7): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (174, 14): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (183, 18): Suspend function 'findCameraView' should be called only from a coroutine or another suspend function
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (184, 7): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (185, 14): Suspend function 'focus' should be called only from a coroutine or another suspend function
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (185, 14): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (230, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (231, 32): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (234, 51): Unresolved reference: isNotEmpty
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (236, 19): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (241, 16): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (243, 15): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (249, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (254, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\CameraViewModule.kt: (259, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\FpsSampleCollector.kt: (4, 26): Unresolved reference: schedule
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\FpsSampleCollector.kt: (7, 28): Unresolved reference: mutableListOf
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\FpsSampleCollector.kt: (11, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\FpsSampleCollector.kt: (12, 12): None of the following functions can be called with the arguments supplied: 
public open fun schedule(p0: TimerTask!, p1: Date!, p2: Long): Unit defined in java.util.Timer
public open fun schedule(p0: TimerTask!, p1: Long, p2: Long): Unit defined in java.util.Timer
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\FpsSampleCollector.kt: (13, 16): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\FpsSampleCollector.kt: (18, 12): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\FpsSampleCollector.kt: (19, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\FpsSampleCollector.kt: (27, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
The class is loaded from C:/Users/Margot/.gradle/caches/transforms-3/fd49cc402b4b657cf2e03265b0eeffbf/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\FpsSampleCollector.kt: (27, 38): Cannot infer a type for this parameter. Please specify it explicitly.
e: C:\Users\Margot\Documents\RVO-APP\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\react\FpsSampleCollector.kt: (28, 30): Overload resolution ambiguity: 

Do you have any idea why?

Thanks a lot !

**Comment by denisbevilacqua** [comment]
Hey @margotbignon! Maybe you can try updating your `android/build.gradle` file to ensure Kotlin version consistency across your project. In the buildscript section, specify a compatible Kotlin version like `1.8.0`:

```gradle
buildscript {
    ext.kotlin_version = "1.8.0"
    ...
}
dependencies {
   //...
    classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
}
```

In the `android/app/build.gradle` file add at the top:

```gradle
apply plugin: "org.jetbrains.kotlin.android"
```

After that, run `/.gradlew clean` comand inside de Android folder, and then remove `android/.gradle` and `android/build` folders.

**Comment by gev2002** [comment]
Hey @margotbignon. I see the problem, but it's not from this package. You can try clearing all caches and rebuilding the project. @denisbevilacqua has a good hint.

**Comment by gev2002** [comment]
**This issue is not related to this package and may be closed.**
