### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by daveyjones** [gev2002/react-native-vision-camera-text-recognition#2]
I'm just getting empty results on iOS:

```
{"result": {"blocks": [], "text": ""}}
{"result": {"blocks": [], "text": ""}}
{"result": {"blocks": [], "text": ""}}
...
```

I created a minimal repository that demonstrates this issue:

https://github.com/daveyjones/vision-camera-text-recognition-demo

**Comment by gev2002** [comment]
It's from orientation you can for a time set orientation={"landscape-left"} for iOS.It's because Vision Camera not fully supported orientation.

**Comment by daveyjones** [comment]
@gev2002 When I use `orientation={"landscape-left"}`, it works correctly in portrait, but ironically does not work in landscape. Do you know how we can support any orientation?
