### ISSUE TITLE
Difference between this and v3

### ISSUE THREAD

**Issue by aabmets** [gev2002/react-native-vision-camera-text-recognition#4]
Hey, sorry for bothering you through GitHub Issues, I couldn't find another venue to contact you.
I see that you also have a [v3](https://github.com/gev2002/react-native-vision-camera-v3-text-recognition) of text-recognition library and the same for other repos as well. I was wondering, could you please help me decide which should I use for my project? Also, do you think I would be able to use your ML Kit project as a template to implement the Google ML document scanning toolkit into the react-native-vision-camera as a plugin the same way your libraries do for text-recognition? Note: I have no prior Kotlin experience, but I am very good with Python.

**Comment by gev2002** [comment]
Hi, you can contact me via Gmail. My address: gev.avet.02@gmail.com
