### ISSUE TITLE
when passing image path to the function PhotoRecognizer this error is coming

### ISSUE THREAD

**Issue by rajaneeshvommi** [gev2002/react-native-vision-camera-text-recognition#6]
Hi, I trying to get the data from the image using the PhotoRecognizer but something is wrong with the image resizer please see the below screenshot for detail error 
![Screenshot_1718959117](https://github.com/gev2002/react-native-vision-camera-text-recognition/assets/16821029/f5acd9f5-d62f-4900-b702-7d722de8ba68)

click event code 
  const pickImageFromGallery = async () => {
    const result = await launchImageLibrary({ mediaType: 'photo', quality: 1 });
    if (result.assets && result.assets.length > 0) {
      const { uri, width, height } = result.assets[0];
      console.log(uri,"image path");
      const result2 = await PhotoRecognizer({
        uri: uri,
        widths: width,
        height: height
    })
    console.log(result2, "result2");
    }
  };

used dependencies 
 "dependencies": {
    "@bam.tech/react-native-image-resizer": "^3.0.10",
    "react": "18.2.0",
    "react-native": "0.74.2",
    "react-native-image-picker": "^7.1.2",
    "react-native-vision-camera": "^4.3.2",
    "react-native-vision-camera-text-recognition": "^3.0.2",
    "react-native-worklets-core": "^1.3.3"
  }

thanks in advance

**Comment by rajaneeshvommi** [comment]
I have tried another example it started working but the text is not showing up it say the possible unhandled promise rejection i:0 
Error : error processing image  waring 
![Uploading Screenshot_1718961841.png…]()

**Comment by gev2002** [comment]
In first variant you are written wrong prop name should be width not widths.
Now I change the logic of the module width and height are no longer necessary, instead you can use orientation for iOS

**Comment by rajaneeshvommi** [comment]
@gev2002 Thank you. sorry about the typo of width, sure I will try and let you know.
